Repository GamerSoft24/Software, pull requests merged in 2024-03, with the labels that each got.

#36 Error handling in PySoft? Issue #34
  Errors chart.md
  PySoft/Calculators/advanced calculator.py
  PySoft/Calculators/basic calculator.py
  PySoft/Editors/gui-text editor.py
  PySoft/Games/code rain.py
  PySoft/Games/error generator.py
  PySoft/Games/guess a number (top 100).py
  PySoft/Games/hangman.py
  PySoft/Games/happy new year 2024!!.py
  PySoft/Games/login simulator.py
  PySoft/Games/rainbow void.py
  PySoft/Games/tic-tac-toe.py
  PySoft/Utilities/iPCMD.py
  PySoft/Utilities/security management system.py
Labels: enhancement, help wanted

#39 this ain't a game, this is actually smth useful
  PySoft/Utilities/pence to pound converter.py
Labels: documentation

#40 Update windows360 aio.bat
  BatchSoft/Windows/windows360 aio.bat
Labels: enhancement

#45 Update Programs.md PySoft
  Programs.md
Labels: enhancement, help wanted

#50 Update README.md v8.0.3 REP-SET I
  README.md
Labels: enhancement
