Repository GamerSoft24/Software, pull requests merged in 2025-03, with the labels that each got.

#67 this has taken toooooo long (more than 1 year?!)
  Programs.md
Labels: bug, documentation, invalid, other

#70 Update .gitattributes *.jar TEST
  .gitattributes
Labels: enhancement, testing

#74 is this how formatting works?
  README.md
Labels: bug, enhancement, testing, other
